# Raising Exception

![Exception hierarchy](exception.jpg)

## `Kernel#raise`

* Default exception raised is **RuntimeError**

~~~ruby
def print_msg(msg)
  if msg.nil?
    raise "msg cannot be nil"
  end

  puts "Message: #{msg}"
end

# raises ArgumentError
print_msg

# raises RuntimeError
print_msg(nil)

# raising required exception
def print_msg2(msg)
  raise ArgumentError, "msg cannot be nil" if msg.nil?
  puts "Message: #{msg}"
end
print_msg2(nil)
~~~

## Defining custom exceptions

~~~ruby
class MyError < StandardError
end
~~~

## Handling exception

* Method definition is an implicit `begin-end` block

* Once the exception is handled, execution continues immediately after the begin block that spawned it.

* `rescue` clause without parameter defaults to `StandardError`.

* `rescue` can accept any parameter that is an instance which derives from `Exception` class. It can also accept any expressions like method calls that returns an instance derived from `Exception` class.

* Within rescue we can reraise the exception using `raise`.

* `ensure` block will always be run.

* `begin-rescue-ensure-else-end` block can be nested inside another `begin` block

~~~ruby
# exception handling syntax
def process(*args)
  begin
    # processing logic
  rescue [Specific_Exception1]
    # exception_handling_logic
  rescue [Specific_Exception1] as => e1
    # exception_handling_logic
    puts e1.message
    puts e1.backtrace
  rescue [Generic_Exception] => e2
    # exception_handling_logic
    raise e2 # reraise exception
  ensure
    # like finally clause in other programming languages
    # this block of code is executed irrespective of some or no exception
  else
    # logic when there is no exception in the begin block
    #  begin block executed successfully
  end
end
~~~

Example of exception handling

~~~ruby
def get_file_contents(file_name)
  begin
    # code to fetch the user details
    raise ArgumentError, "file_name cannot be nil" if file_name.nil?

    lines = File.open(file_name, "r") { |file| file.readlines}
    lines.each {|line| puts line}
  rescue StandardError => e
    puts e.class
    puts e.message
    puts e.backtrace
    puts ex.cause
    puts "exception raised"
    raise e.exception
  end
end

get_file_contents("")
~~~

## `retry` statement

* Retries an exception block.

~~~ruby
def method_with_retry
  retry_count = 0
  begin
    puts "Retry count: #{retry_count}. Hello World"
    raise
  rescue
    if retry_count < 3
      retry_count += 1
      retry
    end
  end
end
~~~

---

## References

* [Raising Exception](http://rubylearning.com/satishtalim/ruby_exceptions.html)
